### ISSUE TITLE
Feature: Define and load a backup specification in YML format

### ISSUE THREAD

**Issue by jdehaan** [Color-Of-Code/backup-rsync#3]
The specification shall declaratively list devices and partitions to backup

```yaml
devices:
  disk1:
    name: 
    comment:
    uuid: partition table uuid
partitions:
  - partA: partition uuid
  - partB:
jobs:
...
```

To be defined
